# Generated by Django 3.2.4 on 2021-07-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_mediablob_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediablob',
            name='data',
            field=models.CharField(max_length=1038336, null=True),
        ),
    ]
