# Generated by Django 3.2.4 on 2021-07-15 05:57

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_mediablob_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediablob',
            name='data',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=10383360, null=True),
        ),
    ]
